### ISSUE TITLE
The claimed history is inaccurate (and "rose-coloured")

### ISSUE THREAD

**Issue by chaals** [w3ctag/ethical-web-principles#100]
Some statements about the Web's history in the Introduction appear to go beyond observed reality:

> One of the web platform's differentiators has always been a strong ethical framework; for example an emphasis on [internationalization](https://www.w3.org/International/), [accessibility](https://www.w3.org/WAI/), [privacy](https://www.w3.org/Privacy/), and [security](https://www.w3.org/Security/). 

It is not at all clear that this has "always" been the case, nor that ethical considerations have been the key drivers of this work.

> Web technologies are also offered [royalty free](https://www.w3.org/Consortium/Patent-Policy/) to enable open source implementation.

They are not offered royalty free. They are developed in such a way that we *attempt* to offer them royalty free, but this has led to us constraining the power of the Web where W3C participants didn't want to support that goal. It also wasn't the case for the first decade of W3C's existence, and in that time it was not at all clear that it was even a goal - there were many who argued *against* W3C's once-radical "royalty-free" patent policy during the years of its development.

Providing inaccurate history is a serious problem, because those who can point out the inaccuracies easily can use that to suggest the document is based on bad assumptions, and is therefore significantly weaker than it aims to be, if not actually misleading and therefore in the context of this particular document self-defeating.

**Comment by masinter** [comment]
> Some statements about the Web's history in the Introduction appear to go beyond observed reality:

Not just an exaggeration, but completely backwards.

> > One of the web platform's differentiators has always been a strong ethical framework; for example an emphasis on [internationalization](https://www.w3.org/International/), [accessibility](https://www.w3.org/WAI/), [privacy](https://www.w3.org/Privacy/), and [security](https://www.w3.org/Security/).

> It is not at all clear that this has "always" been the case, nor that ethical considerations have been the key drivers of this work.

HTTP 0.9 didn't have any of those qualities, and retrofitting internationalization, accessibility, privacy, and security involved decades of work with not very satisfactory results.  From HTTP 0.9 through HTTP 1.1 the primary concerns were scalability, performance, features, interoperability with other things of secondary concern. 

> > Web technologies are also offered [royalty free](https://www.w3.org/Consortium/Patent-Policy/) to enable open source implementation.

> They are not offered royalty

Royalty-free was an early concern, because of the experience with Gopher.

**Comment by torgo** [comment]
@chaals we discussed this morning and we think we can tweak the wording of both sections both to make it clear that we are not trying to write a history of the web here and also to encompass the nuance of both issues.

**Comment by torgo** [comment]
Closed on the basis of #104.
