### ISSUE TITLE
Feedback on principle 9 - sustainable web

### ISSUE THREAD

**Issue by mrchrisadams** [w3ctag/ethical-web-principles#11]
Hi there!

Thanks for making these principles - it's really cool to see someone talking about a sustainable web here, and it was awesome being able to refer to these at the recent JSConf

I have a question about [principle 9](https://github.com/w3ctag/ethical-web-principles/blob/gh-pages/index.html#L134):

> The web must be an environmentally sustainable platform
> 
> The web, as a whole, is a big consumer of power. New web technologies should not make this situation worse. We will consider power consumption when we introduce new technologies to the web.

I understand this to be about device consumption more than anything else, and all the research I can find points to the web being a sustainability issue in two main areas first (making the devices in the first place, and the emissions from generating energy to power the infrastructure of the web), before we consider end user device energy consumption.

It's a pain, and we should be considerate about user's battery life obviously, but the bigger  sustainability levers tend to come from how we power infrastructure (mostly fossil fuels right now), and rethinking how we use and retain hardware.

The best recent report I've found covering this topic is [from the Shift Project (Lean ICT, released earlier this year)](https://theshiftproject.org/en/lean-ict-2/), but there is also [formal guidance from the GHG Protocol on measuring the environmental impact of ICT too](https://www.ictfootprint.eu/en/ghg-protocol-%E2%80%93-software-factsheet), but it's lengthy and quite dry.

Would you consider something like this, to make the link between sustainability and the web more explicit?

> The web must be an environmentally sustainable platform
> 
> The web, as a whole, is a big source of carbon emissions, because it is a big consumer of power. New web technologies should not make this situation worse. We will consider power consumption and the resulting emissions when we introduce new technologies to the web.

Until we have a web running on entirely green power there is a link between power usage and emissions, and this is a decision people who host sites, or provide connectivity to make the web work can take to see immediate progress.

**Comment by alice** [comment]
Hm, I thought it was more about using technologies like blockchain (and Bitcoin in particular) which have the potential to require massive amounts of power to operate. (I see there is now a business renting entire hydro-electric power stations to mine Bitcoins: https://www.hydrominer.org/h2o/)

I agree, it could use some clarification, and I like the wording around emissions.

**Comment by hadleybeeman** [comment]
[Pull request](https://github.com/w3ctag/ethical-web-principles/pull/15) with suggested edits. Thanks for everyone's help with this!
