### ISSUE TITLE
Extend I18N/L10N to include support for languages and especially cultures

### ISSUE THREAD

**Issue by aphillips** [w3ctag/ethical-web-principles#116]
Section 2.4 The web is for all people
https://www.w3.org/TR/2024/DNOTE-ethical-web-principles-20240319/#allpeople

> We will build internationalization and localization capabilities into our specifications and websites.

This is gratifying to see, but I18N thinks is should be amended a bit.  We think it should include support for different languages and for a diversity of cultures, including not disadvantaging smaller language or cultural communities.

**NOTE WELL: @plehegar This repo lacks horizontal review labels. This issue should have an `i18n-needs-resolution` label.**

**Comment by torgo** [comment]
Thanks @aphillips !  We'll have a look at this soon and come back to you with any proposed changes.

**Comment by torgo** [comment]
We think we've addressed this feedback with #119. Thank you!
