### ISSUE TITLE
Relevant work links?

### ISSUE THREAD

**Issue by torgo** [w3ctag/ethical-web-principles#13]
Should we have links to relevant work listed after each principle or in an appendex to reinforce the point that each one of the principles is backed up by technical work going on somewhere... e.g. credible web, privacy & security, WAI, I18N, etc...

**Comment by lknik** [comment]
That would make a document more complex, and picking examples would be challenging because how to represent very high level principles, with references, to avoid pointing out that this principle is reduced to what the references represent?

**Comment by danbri** [comment]
Most of the document is concerned about the content of standards, and does not talk explicitly about the human processes by which Web standards are made. There are two relevant links which ought to be included, which do address the process aspect: 

* https://www.w3.org/Consortium/cepc/  Code of Ethics and Professional Conduct /cc @koalie
* https://www.w3.org/2019/Process-20190301/ W3C Process Document

The relevance of these two documents is that https://w3ctag.github.io/ethical-web-principles/ doesn't go much deeper than mentioning some key ethical considerations. To actually figure out, spec by spec, what the ethical consequences of a technical design might be, requires careful review by a diverse group of participants. The Process document is W3C's recipe for getting broad review of draft specs, and the Code of Ethics and Professional Conduct tries to ensure that our actual groups are respectful and inclusive and welcoming places where ethical concerns will receive a fair audience when raised. They are both worth mentioning explicitly.

Without well run processes and groups raising and listening to ethical concerns, we risk ending up with specs made by and for a very restricted subset of humanity. This often does not work out well in the technology industry at large, and is worth flagging by pointing to these two documents.

**Comment by koalie** [comment]
> [...]There are two relevant links which ought to be included, which do address the process aspect:
> 
>     * https://www.w3.org/Consortium/cepc/  Code of Ethics and Professional Conduct /cc @koalie
> 
>     * https://www.w3.org/2019/Process-20190301/ W3C Process Document
> [...]

The "evergreen" link for the Process is https://www.w3.org/Consortium/Process/ (and you already have the "evergreen" link for CEPC).

**Comment by hadleybeeman** [comment]
[Pull request](https://github.com/w3ctag/ethical-web-principles/pull/15) with suggested edits. Thanks to each of you for your help with this!

**Comment by hadleybeeman** [comment]
Addressed in [pull request](https://github.com/w3ctag/ethical-web-principles/pull/15) and merged at [TAG Cupertino face-to-face](https://github.com/w3ctag/meetings/blob/gh-pages/2019/12-cupertino/README.md).
