### ISSUE TITLE
Update status to make clear this is a living finding?

### ISSUE THREAD

**Issue by torgo** [w3ctag/ethical-web-principles#14]
Should we update the status to make clear this document will continue to evolve?

**Comment by torgo** [comment]
...also to make it clear(er) that this document is the start of a body of work, or is intended to influence future work.

**Comment by hadleybeeman** [comment]
We've covered this in the [pull request from Tokyo](https://github.com/w3ctag/ethical-web-principles/pull/15/files) (which we are still working on in our f2f in Cupertino).
