### ISSUE TITLE
Individual principles ought to be easier to link to

### ISSUE THREAD

**Issue by danbri** [w3ctag/ethical-web-principles#16]
I am sat in a DID WG meeting at TPAC2019. Blockchain is mentioned every few minutes. 

It would be good if documents such as https://www.w3.org/2019/09/did-wg-charter.html could link directly to express commitment to the principles listed here: each principle should show up in the (respec?) table of contents, have a nice # URI reference, etc. 

At least on mobile, I can't see how I could link directly to "The web must be an environmentally sustainable platform".

**Comment by hadleybeeman** [comment]
Good point -- we're on this now. Thanks!

**Comment by hadleybeeman** [comment]
Addressed in [pull request](https://github.com/w3ctag/ethical-web-principles/pull/15) and merged at [TAG Cupertino face-to-face](https://github.com/w3ctag/meetings/blob/gh-pages/2019/12-cupertino/README.md).
