### ISSUE TITLE
Draw out the openness of specs

### ISSUE THREAD

**Issue by hadleybeeman** [w3ctag/ethical-web-principles#17]
There are ethical as well as legal motivations for us publishing all our specs. 

If anyone is able to implement them -- either by publishing a website or data, or something that can consume them -- then the rules for making that work must be publicly visible on the web. (And legal to implement.)

We should make this explicit in the doc.

**Comment by masinter** [comment]
There are policy choices about whether specs should be freely available, or support "view source" but the link to ethical concerns isn't direct. If you want to make reference to openness, you might want to cite OpenStand (https://open-stand.org, to which W3C is on record as supporting) but draw out more clearly the circumstances under which not following those policies would be considered unethical.

see https://www.youtube.com/watch?v=VFnzPAd6UqI

**Comment by hadleybeeman** [comment]
Addressed in [pull request](https://github.com/w3ctag/ethical-web-principles/pull/15) and merged at [TAG Cupertino face-to-face](https://github.com/w3ctag/meetings/blob/gh-pages/2019/12-cupertino/README.md).
