### ISSUE TITLE
"Web Openness" / "View-source ability" as part of the Design Reviews

### ISSUE THREAD

**Issue by pes10k** [w3ctag/ethical-web-principles#18]
One of the ethical web principals is that the web should be "view source" able.  This aught to be a criteria for design reviews.

i.e. if a new spec moves logic from the client to the server (e.g. client hints moving "what image should i load" logic from `<picture>` to client-server interaction), and makes it harder for users and researchers to audit applications, that should a relevant, strongly-weighing (though possibly (?) not deciding) factor of design reviews.

(apologies if this is the wrong repo for this.  Neither of the options in https://github.com/w3ctag/design-reviews/issues/ seemed correct).

**Comment by hober** [comment]
We tried to capture this in principle 10, "The web is transparent," but if that wasn't clear to you, perhaps it won't be clear to other readers as well. Could you take a look at the existing wording of that principle & suggest improvements?

**Comment by pes10k** [comment]
@hober I think the principal captures it perfectly!  Is this part of TAG review though?  For example, would TAG review turn down something like client-hints for violating principal 10?  

In other words, the document is what put the idea in my head in the first place :) this issue / request is just to understand better if / how / when its applied in TAG review

**Comment by hober** [comment]
> Is this part of TAG review though?

Yes. All TAG findings can/do/should feed into the thinking we put into design reviews. This particular finding is pretty new; I expect you'll see more citations of it in our design reviews going forward.

> For example, would TAG review turn down something like client-hints for violating principal 10?

I don't think I understand this question. The TAG does sometimes decline to review things. For instance, sometimes we choose not to review something because the thing in question is extremely early on in its development and there's not much there to review yet. But maybe you mean something else by "review turn down?"

**Comment by pes10k** [comment]
> I don't think I understand this question. The TAG does sometimes decline to review things. For instance, sometimes we choose not to review something because the thing in question is extremely early on in its development and there's not much there to review yet. But maybe you mean something else by "review turn down?"

Sorry, i worded poorly.  I mean, using the example of client-hints, would TAG find the spec unsuitable / in need of change, because it seems to violate principal 10

**Comment by hober** [comment]
> Sorry, i worded poorly. I mean, using the example of client-hints, would TAG find the spec unsuitable / in need of change, because it seems to violate principal 10

I don't know; IIRC the Client Hints review predates my time on the TAG.

That said, is "Yes. All TAG findings can/do/should feed into the thinking we put into design reviews." a satisfactory answer to the original question? I'd like to resolve this issue if possible. If you'd like, you could separately raise a design review request on Client Hints.

**Comment by pes10k** [comment]
yep, all good and resolved.  thanks!
