### ISSUE TITLE
Draft Finding doesn't link to latest published Finding

### ISSUE THREAD

**Issue by hober** [w3ctag/ethical-web-principles#26]
The [Draft Finding](https://w3ctag.github.io/ethical-web-principles/) doesn't link to the [most recently published Finding](https://www.w3.org/2001/tag/doc/ethical-web-principles/).

**Comment by rhiaro** [comment]
This is because [respec doesn't link the latest version for 'no track' documents](https://github.com/w3c/respec/blob/develop/src/w3c/templates/headers.js#L143), and [`draft-finding` is a 'no track' document](https://github.com/w3c/respec/blob/develop/src/w3c/headers.js#L184).

**Comment by hober** [comment]
> This is because [respec doesn't link the latest version for 'no track' documents](https://github.com/w3c/respec/blob/develop/src/w3c/templates/headers.js#L143), and [`draft-finding` is a 'no track' document](https://github.com/w3c/respec/blob/develop/src/w3c/headers.js#L184).

Ahhh, okay. Filed w3c/respec#3541. Hopefully they'll fix this soon.

**Comment by marcoscaceres** [comment]
Thanks @rhiaro for doing the ReSpec code archeology. I'll get that fixed up soon.

**Comment by LeaVerou** [comment]
This is a small document, how much work would it be to switch it to Bikeshed? We already use Bikeshed for our Design Principles.

**Comment by hober** [comment]
> This is a small document, how much work would it be to switch it to Bikeshed? We already use Bikeshed for our Design Principles.

I think the editors should use whichever tools they prefer.

**Comment by LeaVerou** [comment]
> > This is a small document, how much work would it be to switch it to Bikeshed? We already use Bikeshed for our Design Principles.
> 
> I think the editors should use whichever tools they prefer.

Of course. Nobody said otherwise, I think? 🤔

**Comment by marcoscaceres** [comment]
@LeaVerou, I sent https://github.com/w3ctag/ethical-web-principles/pull/41 to clean up the markup/markdown usage. BikeShed and ReSpec use almost identical syntax and do the same thing, so not sure what advantage there is to switching?

**Comment by torgo** [comment]
This looks to be fixed.
