### ISSUE TITLE
Relationship with Design Principles

### ISSUE THREAD

**Issue by rhiaro** [w3ctag/ethical-web-principles#37]
Note link with Design Principles as the practical "how to" on top of the Ethical Web Principles, but also note that not all EWPs translate directly to API design issues, as there are other parts of the Web platform to consider as well.

**Comment by hadleybeeman** [comment]
Related to https://github.com/w3ctag/design-principles/pull/327

**Comment by torgo** [comment]
So we still need links from EWP to design principles.

**Comment by rhiaro** [comment]
@hadleybeeman and I have been working on this at our f2f, and will add to PR #84 as we progress

**Comment by torgo** [comment]
We agreed today that the info we have in section 1.1 is sufficient for the document and therefore we should not block putting this forward for statement on this issue. We're going to close for now.
