### ISSUE TITLE
The danger of prioritising algorithmic relevance over human needs

### ISSUE THREAD

**Issue by hadleybeeman** [w3ctag/ethical-web-principles#42]
This came from a TAG breakout conversation between me, @plinss, @hober, @atanassov and @LeaVerou. We started by talking about when [Facebook Memories feature evoked traumatic and painful memories](http://meyerweb.com/eric/thoughts/2014/12/24/inadvertent-algorithmic-cruelty/), and moved on to when [Twitter's algorithm cropped out faces with darker skin](https://www.theguardian.com/technology/2020/sep/21/twitter-apologises-for-racist-image-cropping-algorithm), and then [Google's forthcoming "dermatology assist" tool not being trained on darker skin.](https://www.vice.com/en/article/m7evmy/googles-new-dermatology-app-wasnt-designed-for-people-with-darker-skin) 

We narrowed the conversation down to situations where the algorithm is accurate, but the biases in its training data or lack of consideration of the impact of its results make its results accidentally painful, dangerous or otherwise inhumane.
We weren't sure how to translate this into an ethical web principle, so are creating this issue to start the discussion.

**Comment by masinter** [comment]
ML is based on the assumption that past behavior is the best predictor of future behavior when optimizing for an evaluation function. The evaluation optimization is often based on immediate benefit such as stikiness, click-thrus vs. long-term benefit of goodwill, reputation.  As long as most of the value is targeted advertising, follow the money. It might be "accurate" but short-sighted.

**Comment by torgo** [comment]
I'll make a go at seeing what we could write about this in the context of the current principles.... Suggestion from @rhiaro that we could mention this in the intro section maybe?

**Comment by OR13** [comment]
This seems like a good place to leave this:

[Dead Internet Theory, The Internet Is Empty | Esoteric Internet](https://www.youtube.com/watch?v=BEIZHlfjAT8)

The pro/con of knowledge / information tooling is that it shapes learning and behavior in humans...

Most folks tend not to like the idea of being convinced to vote for a politician or buy a product, but they will happily subscribe to a content feed that slowly changes their mind as they upvote / like cat or frog pictures.

**Comment by torgo** [comment]
At this is already covered in the [Web Machine Learning Ethics](https://webmachinelearning.github.io/webmachinelearning-ethics/) document it feels redundant to also put it here. Hence we've agreed to close this issue.
