### ISSUE TITLE
Less Hedging & Add Subheadings

### ISSUE THREAD

**Issue by torgo** [w3ctag/ethical-web-principles#51]
Feedback from: @oluoluoxenfree  

https://twitter.com/oluoluoxenfree/status/1442811890212737024 

<img width="535" alt="image" src="https://user-images.githubusercontent.com/287526/135084003-d20ed1c8-b0c0-4b0c-b208-2dd5b752d36b.png">

We should do a pass-through to strengthen the language (and consider subheads).

**Comment by rhiaro** [comment]
Subheads added in https://github.com/w3ctag/ethical-web-principles/pull/49

**Comment by hadleybeeman** [comment]
Hi @oluoluoxenfree — thanks so much for this! We're looking at your suggestions in our TAG breakout meeting right now. As @torgo says, above, we should do a pass-through to strengthen the language. 

Hoping to get a bit more specific: I see two instances of the terms 'more ethical' in [the document](https://w3ctag.github.io/ethical-web-principles/), both in the introduction. Do you find the entire introduction in need of strengthening? Or is it just the phrase you've mentioned?

Equally, did you notice other phrases or sections of the document that you thought could use rephrasing?

We're grateful for your help in making this stronger and more effective!

**Comment by oluoluoxenfree** [comment]
@hadleybeeman I find all uses of "more ethical" not specific enough.

I assume you went for "more ethical" to highlight that perfect ethics are not attainable and the ethics at current can be improved, but I think in both cases saying the assumed parts loudly is sufficient?

**Comment by oluoluoxenfree** [comment]
I can go line by line, but I'm not sure how helpful that would be, re: other things I would change

**Comment by rhiaro** [comment]
Hi @oluoluoxenfree, I went top to bottom fixing typos and rearranging paragraphs to improve the flow, as well as looking out for language I could strengthen. We merged this earlier (#65). Would you have a chance to look over it and let us know if you think it's an improvement? We've also added language as part of other issues about ethical considerations being contextual and needing balanced against each other, which might go some way towards what you said about "perfect ethics are not attainable".

**Comment by oluoluoxenfree** [comment]
Sorry for the slow response, looks a lot better to me @rhiaro!

**Comment by torgo** [comment]
We discussed and agreed not to do subheadings right now. Hence and considering the positive feedback I'm going to close this issue. Thanks!
