### ISSUE TITLE
Acknowledge that principles can come in conflict with one another

### ISSUE THREAD

**Issue by tobie** [w3ctag/ethical-web-principles#62]
For example transparency (_"We will always make sure it is possible to determine how a web application was built and how the code works."_) can conflict with reducing the web's environmental footprint (shipping binary data would probably be more efficient), preventing the spread of misinformation may conflict with privacy, enabling users to render their content as they please may conflict with security concerns, etc.

Some principles acknowledge this tension, for example in [§2.6 The web must enable freedom of expression](https://w3ctag.github.io/ethical-web-principles/#expression): _"Our work should not enable state censorship, surveillance or other practices that seek to limit this freedom. This principle must be balanced with respect for other human rights […]"._

It would be good to acknowledge this in general, maybe right after the introduction or in conclusion.

**Comment by lknik** [comment]
Interesting problem. Indeed it is imaginable that certain principles will be in conflict with others. What then?

**Comment by mnot** [comment]
Competing interests are often balanced in courts, the WTO, etc. One thing we should put some thought into is how to avoid the outcomes of balancing being considered arbitrary -- people need certainty. That might be through deeper documentation/exploration of the principles over time (as well already do e.g., for privacy). As the very high, abstract level the current principles are, this is going to be difficult.

**Comment by torgo** [comment]
Closed to to merge of #64
