### ISSUE TITLE
Clarify that EWP should also be used when reviewing updates to existing specs 

### ISSUE THREAD

**Issue by tobie** [w3ctag/ethical-web-principles#67]
The language of the document focuses on informing the review of new specs, see for example:

> The purpose of this document is to inform TAG review of new specifications and to inform other documents such as the Web Platform Design Principles, Self-Review Questionnaire: Security and Privacy or other similar checklists and sets of principles used by specification authors and editors.

#66 makes the point that there's no reason for the principles to not be used while reviewing amendments to existing specs, for example by changing the above paragraph to:

> The purpose of this document is to inform TAG review of new specifications **_and candidate additions to published recommendations_** and to inform other documents such as the Web Platform Design Principles, Self-Review Questionnaire: Security and Privacy or other similar checklists and sets of principles used by specification authors and editors.

**Comment by torgo** [comment]
Closed due to merge of #64
