### ISSUE TITLE
Conflicts between principles

### ISSUE THREAD

**Issue by twifkak** [w3ctag/ethical-web-principles#7]
Often situations arise where there is an unavoidable trade-off between two principles. (This may be a simple trinary "pick two" scenario, or a more complicated continuum between various aspects.)

The document may want to offer advice on how authors/editors should handle these trade-offs. Are some principles always preferred above others? Are there some rough preferences where a major (high impact and/or likelihood) improvement in one aspect is worth a minor (low impact and/or likelihood) reduction in another? Are all principles equal in priority?

**Comment by twifkak** [comment]
There's another option of "Don't make changes unless they're neutral to positive on all axes." This seems to be dependent on #8, or else one should evaluate change X in equal footing to "pretend we have X, now undo it", in which case we have stalemate.

**Comment by dbaron** [comment]
> The document may want to offer advice on how authors/editors should handle these trade-offs. Are some principles always preferred above others? Are there some rough preferences where a major (high impact and/or likelihood) improvement in one aspect is worth a minor (low impact and/or likelihood) reduction in another? Are all principles equal in priority?

I think relatively straightforward answers are no, yes, and no.  I think it's generally possible for a particular technical decision to have either a small or large effect on something related to one of the principles.  I realize that doesn't provide a lot of guidance to spec authors and editors, though.  But in general I think the relevant tradeoffs around a decision should be considered.

**Comment by hadleybeeman** [comment]
It sounds like this issue is more about how the doc is used than what is in its content.

Inevitably, these principles will be weighted differently in each context where they are used. And that's a good thing... We are representing our experiences and discussions to date, not making the authoritative decision tree for how to make an ethics decision when writing a new spec.

My suggestion would be to leave this kind of logic for the spec author (with the TAG, if they ask for our help) to work out when they're designing something. 

How does that sound? Is there anything you see in the document that makes that complicated or a bad idea, @twifkak?

**Comment by twifkak** [comment]
@hadleybeeman Yeah, I think leaving it up to individual interpretation is a reasonable approach (at least until further experience helps discover some commonality between the case-by-case decisions).

I think the only thing in the document that counters that interpretation is that some of the statements are phrased as absolutes. Just a few examples:

 - we will build them to cross regional and national boundaries
 - We will prioritise potential benefits for users over potential benefits to web developers
 - The web must support healthy community and debate
 - We ... will build web technologies and platforms that respect individuals' rights
 - We will build internationalization and localization capabilities into our specs and websites
 - We must make our websites accessible for people with disabilities.

Perhaps changing "will" to "will try to" or "ought to" better communicates the intent, then?

**Comment by masinter** [comment]
Is there a good reason not to use RFC 2119 / BCP 14 keywords and choose
between **should** and **must**?
3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

**Comment by torgo** [comment]
Just discussing with @hadleybeeman today. We see where you're coming from. However, we think that the use of e.g. SHOULD in place of the informal "will" waters down what we are trying to achieve here. In the end, this is not a spec. It's more like a "manifesto" style document in that it is a set of affirmative statements. The documents that this list will inform the content of will have to conform to more rigorous language (e.g. 2119 type statements). But we don't think it's appropriate for the finding.

**Comment by twifkak** [comment]
Yup, I totally appreciate that this is to have emotional appeal, and that precision of language is a secondary priority to that. My general fear is imprecise language being used inconsistently in order to effect hidden agendas. But understood that this is a trade-off of risks. I trust y'all to make the right call; just wanted to make sure it got some thought.

**Comment by hadleybeeman** [comment]
Thanks for your careful thought and effort here, @twifkak. We appreciate you trying to help us make this better!
