### ISSUE TITLE
Unlock #66

### ISSUE THREAD

**Issue by frabaghe** [w3ctag/ethical-web-principles#70]
> I thought we were on a good track with discussion of a potential rewording of our sustainability issue. Unfortunately this issue has devolved into name calling. I'm calling time out on this discussion, freezing the issue, and putting a temporary ban on certain individuals.

Would it be possible to unlock #66? The overall conversation was productive, in my view, and I'd very much like to be able respond to points in the issue that I opened. Thanks. 🙏

**Comment by torgo** [comment]
Hi @frabaghe we're in the process of putting together some text on this topic to try to move the issue along - it's not ready yet. the proposal is to close #66 when we make that proposal and then use the PR to discuss / agree the text change.

**Comment by frabaghe** [comment]
@torgo while I appreciate that direction 👍 , I'm not sure I understand why #66 needs to remain locked. The conversation was and can still be productive in the meantime and there are issues that I'd like to address _before_ text is drawn up.
