### ISSUE TITLE
Concerns with quick merge of Issue #72

### ISSUE THREAD

**Issue by vsnt** [w3ctag/ethical-web-principles#74]
It was brought to the attention of the Credentials Community Group on March 22, that TAG issue #72 was resolved and merged without allowing sufficient time to be reviewed by the broader community. This is in no way a reflection on the solution, but a request to allow time for the community to give feedback prior to merging. https://github.com/w3ctag/ethical-web-principles/pull/72

CCG co-chairs request this issue be re-opened in order to accept feedback from the broader community for at least 3 days before being committed.

Thank you cc @mprorock @kwlinson @rxgrant

**Comment by hober** [comment]
I think perhaps you misapprehend the TAG's process, @vsnt. Please do file concrete issues on the current text of the document!

**Comment by torgo** [comment]
Hi - agree with Tess. We are totally open to additional feedback. We try to iterate quickly rather than waiting for "perfect" text before we merge. If the CCG would would like to make suggestions, please open a new issue. Thanks!

**Comment by vsnt** [comment]
Hi, I'm re-opening this thread, per the request of someone in the CCG, who has comments. You closed this issue before the comments could be raised! 

Could you please leave it open to allow for time for them to respond? This was open for less than an hour and that's next to no time to allow for someone to reply. Thank you.

**Comment by rxgrant** [comment]
I've added my comment [on pull #72](/w3ctag/ethical-web-principles/pull/72#issuecomment-1081486664).
