### ISSUE TITLE
Grammatical consistency of principles

### ISSUE THREAD

**Issue by rhiaro** [w3ctag/ethical-web-principles#75]
Some principles are "should", some are "must" and some simply "are". Can we make them consistent? I propose aligning on "are" (as aspirational, rather than currently true) but don't have strong feelings. ie:

* There is one web
* The web **does** not cause harm to society
* The web **supports** healthy community and debate
* The web is for all people
* **The web is secure and respects peoples' privacy**
* The web **enables** freedom of expression
* The web **makes** it possible for people to verify the information they see
* The web **enhances** individuals' control and power
* The web **is** an environmentally sustainable platform
* The web is transparent
* The web is multi-browser, multi-OS and multi-device
* People **can** render web content as they want

**Comment by torgo** [comment]
@hadleybeeman can you comment?

**Comment by hadleybeeman** [comment]
Discussed in [face-to-face in London](https://github.com/w3ctag/meetings/blob/gh-pages/2022/07-London/README.md)

**Comment by rhiaro** [comment]
* There is one web
* The web should not cause harm to society
* The web **should** support healthy community and debate
* The web **should be** for all people
* **The web should be secure and privacy-respecting**
* The web **should** enable freedom of expression
* The web **should** make it possible for people to verify the information they see
* The web **should** enhance individuals' control and power
* The web **should** be an environmentally sustainable platform
* The web **should be** transparent
* The web **should be** multi-browser, multi-OS and multi-device
* People should be able to render web content as they want
