### ISSUE TITLE
"Minimal change" principle?

### ISSUE THREAD

**Issue by twifkak** [w3ctag/ethical-web-principles#8]
I presume that, all else being equal, the minimal change to the web platform should be preferred. It's unclear to me whether this should be called out as a separate principle, or if it follows obviously enough from "for all people" (including people with old user agents) and "multi-browser, multi-OS and multi-device" (given they may have different criteria before adopting changes to the platform).

On the other hand, it conflicts with others, such as "Security and privacy are essential" (as our knowledge about security practices improves over time), so perhaps it's best left implicit.

**Comment by hober** [comment]
There were a few proposed HTML design principles that touched on this, several of which made it into [that document](https://www.w3.org/TR/html-design-principles/) (Pave the Cowpaths, Evolution Not Revolution, Avoid Needless Complexity) and one that (sadly, IMHO) did not ([Baby Steps](https://www.w3.org/html/wg/wiki/DesignPrinciplesReview#Baby_Steps)).

**Comment by dbaron** [comment]
This seems like it might be a reasonable practical principle (although I tend to think it's not true all the time, and might be better derived from other principles in the cases where it is good).  But I don't think it's an ethical principle that belongs in this document.

**Comment by torgo** [comment]
@hadleybeeman & I discussed and we feel that while this may be a good design principle it's not strictly an ethical principle in itself. Maybe this discussion belongs in the https://github.com/w3ctag/design-principles document?  Or maybe we need a separate finding covering this topic?

**Comment by torgo** [comment]
We're going to close this as we are tidying up to issue an update.
