### ISSUE TITLE
Protect vs Control

### ISSUE THREAD

**Issue by mnot** [w3ctag/ethical-web-principles#80]
> When we add features to the web platform, we are making decisions that may change the ability of people to protect their personal data

protect doesn't capture all aspects; this would be better as 'control'

**Comment by mnot** [comment]
To extend a bit - 

Privacy is more than just data protection. While data protection is largely about the processes and technical measures taken to assure that data is handled correctly (e.g., preventing unauthorised access), privacy encompasses a much wider scope, including fundamental issues like human dignity, and yes -- the ability to control your data.

**Comment by torgo** [comment]
Totally agree with what you wrote above. We think the issue may be about the word “protect” which we mean more in the wider sense rather than in the context of “data protection”. We’ll work on it.
