### ISSUE TITLE
Honouring expectations

### ISSUE THREAD

**Issue by mnot** [w3ctag/ethical-web-principles#82]
It might be good to explicitly establish that surprising web users is unethical. Over the years, people have built a mental model of how the web works, and if the underlying technology changes in ways that break their expectations, that's an issue.

For example, the use of HTTPS has always implied that communication between the origin server and the browser is protected from modification and observation (unless the user explicitly opts into interception by installing a CA cert). However, folks came to the HTTP WG asking to allow a "good" intermediary to automatically inject itself, perhaps with an icon indicating that it was happening. Doing so would violate user expectations about how the web works.

**Comment by rhiaro** [comment]
@torgo, @hadleybeeman and I discussed this in our f2f today. After some wordsmithing, we landed on:

> Web platform technologies should behave consistently and intuitively.

As an addition to "The web is for all people" to address this point (using as simple language and as few words as possible!).
