### ISSUE TITLE
Complexity as an ethical issue

### ISSUE THREAD

**Issue by mnot** [w3ctag/ethical-web-principles#83]
Should the document say anything about the burden of complexity on users? 

For example, security user experience (such as the browser lock icon and cert warning dialogue) has gone through a long journey informed by user testing that shows that even though people value their security, they tend to click through things to get what they want. 

Arguably, we shouldn't expect users to form a sophisticated, nuance model of the web and how it works in detail, and they shouldn't have to do a lot of site-by-site labour to use the web in the way they want.

This has obvious implications for privacy too.

**Comment by dbaron** [comment]
I agree with your point about security user experience, and I think I likely also agree with your point about complexity.

However, I'm not sure that complexity is the best underlying principle to use to explain the point about security user experience point you're making.  I think that it might be more clearly demonstrating that it's hard to get meaningful consent when you're asking for that consent in the critical path of some other task.

I'd be interested to see other examples that demonstrate the complexity point more directly.

**Comment by mnot** [comment]
Not an example per se, but to me this is also one of the fundamental points of Roy's thesis and REST -- complexity in interfaces creates cognitive overload.

Examples are hard to find because we already strive to reduce user-visible complexity where possible; it's when new folks show up and want to solve their problems by increasing complexity that we have a problem.

Using that lens, I'd say the reason we align on same-origin for a security boundary is to reduce complexity; if everything aligned differently, it'd be more difficult to comprehend and reason about. (insert implications for first-party sets).

**Comment by rhiaro** [comment]
@torgo, @hadleybeeman and I discussed this in our f2f today. After some wordsmithing, we landed on:

> People should not need a high level of technical literacy to use the web.

As an addition to "The web is for all people" to address this point (using as simple language and as few words as possible!).
