### ISSUE TITLE
Right to be forgotten

### ISSUE THREAD

**Issue by pirate** [w3ctag/ethical-web-principles#9]
Users should have a right to delete their data and request it be de-listed from search engines.

As someone who works on internet archiving, I have to think about this principle a lot when designing digital preservation mechanisms, the right to remove must always be considered.

- https://en.wikipedia.org/wiki/Right_to_be_forgotten
- https://gdpr-info.eu/art-17-gdpr/
- https://gdpr-info.eu/issues/right-to-be-forgotten/

**Comment by lknik** [comment]
I would assume RTBF is more about privacy, so not convinced it should be included in the existing published document on ethics.
