### ISSUE TITLE
URL not rendering; missing 'to'?

### ISSUE THREAD

**Issue by jbradleychen** [w3ctag/ethical-web-principles#98]
From https://w3ctag.github.io/ethical-web-principles/#verify
> The concept of origin and [its relationship information sources](https://www.w3.org/2001/tag/doc/distributed-content/) are core to the web's security model.

I don't understand why the URL is not rendering properly. Also I don't understand what is meant by "its relationship information sources". Maybe a "to" is missing?

**Comment by rhiaro** [comment]
I think this has been fixed as part of an earlier edit, as the link and the grammar is correct in the current gh pages version
